import Link from "next/link";
import { Bell, CalendarDays, ClipboardList, FileText, LayoutDashboard, LogOut, Pill, ShieldCheck, Users } from "lucide-react";
import { logoutAction } from "@/app/actions/auth";
import { MobileMenu } from "@/components/mobile-menu";
import { requireUser } from "@/lib/session";

const links = [["/", "Dashboard", LayoutDashboard], ["/patients", "Patients", Users], ["/appointments", "Appointments", CalendarDays], ["/queue", "Daily queue", ClipboardList], ["/follow-ups", "Follow-ups", Bell], ["/medicines", "Medicines", Pill], ["/staff", "Staff", ShieldCheck], ["/audit", "Audit log", FileText]];
export default async function ClinicLayout({ children }: { children: React.ReactNode }) {
  const user = await requireUser();
  return <main className="min-h-screen bg-[#f7f8fc] text-slate-900"><aside className="fixed inset-y-0 left-0 hidden w-60 flex-col border-r border-slate-200 bg-white px-4 py-6 lg:flex"><Link href="/" className="mb-9 flex items-center gap-3 px-2"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#3766f5] text-xl font-black text-white">+</span><span><b className="block text-lg">Shiva Dental Clinic</b><small className="text-slate-400">Management System</small></span></Link><nav className="space-y-1">{links.filter(([, label]) => !["Audit log", "Staff"].includes(label as string) || user.role === "ADMIN").map(([href, label, Icon]) => <Link key={href as string} href={href as string} className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium text-slate-500 hover:bg-[#edf1ff] hover:text-[#315ce7]"><Icon size={18}/>{label as string}</Link>)}</nav><div className="mt-auto rounded-xl bg-slate-50 p-3"><p className="text-sm font-bold">{user.name}</p><p className="mb-3 text-xs text-slate-400">{user.role.toLowerCase()}</p><form action={logoutAction}><button className="flex items-center gap-2 text-xs font-semibold text-slate-500"><LogOut size={15}/>Sign out</button></form></div></aside><section className="lg:pl-60"><header className="flex h-16 items-center justify-between border-b border-slate-200 bg-white px-5 lg:px-8"><div className="flex items-center gap-2 lg:hidden"><MobileMenu role={user.role}/><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#3766f5] font-bold text-white">+</span><b>Shiva Dental Clinic</b></div><p className="hidden text-sm text-slate-400 lg:block">Shiva Dental Clinic WorkSpace</p><span className="rounded-full bg-[#edf1ff] px-3 py-1 text-xs font-bold text-[#315ce7]">{user.role}</span></header><div className="mx-auto max-w-7xl p-5 lg:p-8">{children}</div></section></main>;
}
