"use client";

import { updatePatientAction } from "@/app/actions/clinic";
import { SubmitButton } from "@/components/submit-button";

type Patient = { id: string; firstName: string; lastName: string; mobile: string; email: string | null; dateOfBirth: Date | null; gender: string | null; address: string | null; allergies: string | null };

export function PatientEditForm({ patient }: { patient: Patient }) {
  return <form action={updatePatientAction} className="space-y-4"><input type="hidden" name="id" value={patient.id}/><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">First name <span className="text-red-500">*</span><input name="firstName" required defaultValue={patient.firstName} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label><label className="text-sm font-semibold">Last name <span className="text-red-500">*</span><input name="lastName" required defaultValue={patient.lastName} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label><label className="text-sm font-semibold">Mobile <span className="text-red-500">*</span><input name="mobile" required defaultValue={patient.mobile} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label><label className="text-sm font-semibold">Email<input name="email" type="email" defaultValue={patient.email ?? ""} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label><label className="text-sm font-semibold">Date of birth<input name="dateOfBirth" type="date" defaultValue={patient.dateOfBirth?.toISOString().slice(0,10) ?? ""} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label><label className="text-sm font-semibold">Gender<input name="gender" defaultValue={patient.gender ?? ""} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label></div><label className="block text-sm font-semibold">Address<textarea name="address" rows={2} defaultValue={patient.address ?? ""} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label><label className="block text-sm font-semibold">Known allergies<textarea name="allergies" rows={2} defaultValue={patient.allergies ?? ""} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal"/></label><SubmitButton pendingLabel="Updating..." className="rounded-xl bg-[#3766f5] px-4 py-2.5 text-sm font-bold text-white">Save patient details</SubmitButton></form>;
}
